import {json,getCustomer} from '../../_lib/customer-auth.js';
const num=v=>Number(v||0);
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_favorites(customer_id INTEGER NOT NULL,product_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(customer_id,product_id),FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)`).run()}
const productShape=x=>({id:num(x.id),slug:x.slug,sku:x.sku,name:x.name,description:x.description,category:x.category,price:num(x.price),compareAtPrice:x.compare_at_price==null?null:num(x.compare_at_price),rating:num(x.rating),soldCount:num(x.sold_count),stock:num(x.stock),featured:Boolean(num(x.featured))});
export async function onRequestGet({request,env}){if(!env.DB)return json({error:'database_not_bound'},503);const c=await getCustomer(request,env);if(!c)return json({authenticated:false},401);await ensure(env);const [favR,recentR,boughtR,productsR]=await Promise.all([
  env.DB.prepare(`SELECT f.product_id,p.category FROM customer_favorites f JOIN products p ON p.id=f.product_id WHERE f.customer_id=? AND p.active=1 ORDER BY f.updated_at DESC LIMIT 40`).bind(c.customer_id).all(),
  env.DB.prepare(`SELECT cr.product_id,p.category,cr.viewed_at FROM customer_recent_products cr JOIN products p ON p.id=cr.product_id WHERE cr.customer_id=? AND p.active=1 ORDER BY cr.viewed_at DESC LIMIT 30`).bind(c.customer_id).all(),
  env.DB.prepare(`SELECT oi.product_id,p.category,p.slug,p.sku,p.name,p.description,p.price,p.compare_at_price,p.rating,p.sold_count,p.stock,p.featured,MAX(o.created_at) last_bought_at,SUM(oi.qty) qty FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id WHERE o.customer_id=? AND o.status!='cancelled' AND p.active=1 GROUP BY oi.product_id ORDER BY last_bought_at DESC LIMIT 30`).bind(c.customer_id).all(),
  env.DB.prepare(`SELECT p.id,p.slug,p.sku,p.name,p.description,p.category,p.price,p.compare_at_price,p.rating,p.sold_count,p.stock,p.featured,COALESCE(e.views,0) views,COALESCE(e.clicks,0) clicks,COALESCE(e.carts,0) carts,COALESCE(e.purchases,0) purchases FROM products p LEFT JOIN (SELECT product_id,SUM(CASE WHEN event_type='content_view' THEN 1 ELSE 0 END) views,SUM(CASE WHEN event_type='product_pin_click' THEN 1 ELSE 0 END) clicks,SUM(CASE WHEN event_type='add_to_cart' THEN 1 ELSE 0 END) carts,SUM(CASE WHEN event_type='purchase' THEN 1 ELSE 0 END) purchases FROM commerce_events WHERE created_at>=datetime('now','-30 day') AND product_id IS NOT NULL GROUP BY product_id)e ON e.product_id=p.id WHERE p.active=1 AND p.stock>0 LIMIT 200`).all()
]);
 const fav=favR.results||[],recent=recentR.results||[],bought=boughtR.results||[],products=productsR.results||[];const category=new Map(),favIds=new Set(fav.map(x=>String(x.product_id))),boughtIds=new Set(bought.map(x=>String(x.product_id)));
 fav.forEach(x=>category.set(x.category,(category.get(x.category)||0)+9));recent.forEach((x,i)=>category.set(x.category,(category.get(x.category)||0)+Math.max(1,6-i*.15)));bought.forEach(x=>category.set(x.category,(category.get(x.category)||0)+Math.min(18,6+num(x.qty)*2)));
 const recentRank=new Map(recent.map((x,i)=>[String(x.product_id),Math.max(0,28-i)]));const scored=products.map(p=>{let score=(category.get(p.category)||0)+(favIds.has(String(p.id))?18:0)+(recentRank.get(String(p.id))||0)+(boughtIds.has(String(p.id))?8:0)+num(p.featured)*10+num(p.rating)*4+Math.min(25,num(p.sold_count)/100)+Math.min(18,num(p.clicks)*.2)+Math.min(24,num(p.carts)*.45)+Math.min(30,num(p.purchases)*1.5);return {...p,score:Math.round(score*100)/100}}).sort((a,b)=>b.score-a.score||num(b.sold_count)-num(a.sold_count)).slice(0,12);
 return json({authenticated:true,profile:{favorites:fav.length,recent:recent.length,purchasedProducts:bought.length},recentlyBought:bought.slice(0,8).map(x=>({...productShape(x),lastBoughtAt:x.last_bought_at,qty:num(x.qty)})),recommendations:scored.map(x=>({...productShape(x),score:x.score}))});}
