import {test,expect} from '@playwright/test';
const products=[
{id:901,slug:'rang-jued-tea-e2e',sku:'E2E-TEA-901',name:'ชารางจืดสำหรับทดสอบระบบ',description:'ข้อมูลสำหรับทดสอบเส้นทางเลือกซื้อเท่านั้น',category:'ชาสมุนไพร',price:190,compare_at_price:null,rating:0,sold_count:0,stock:5,featured:1,sale_verified:1,image_url:'/assets/products/rang-jued-tea-360.webp'},
{id:902,slug:'chiang-da-tea-e2e',sku:'E2E-TEA-902',name:'ชาเชียงดาสำหรับทดสอบระบบ',description:'ข้อมูลสำหรับทดสอบเส้นทางเลือกซื้อเท่านั้น',category:'ชาสมุนไพร',price:220,compare_at_price:null,rating:0,sold_count:0,stock:5,featured:1,sale_verified:1,image_url:'/assets/products/chiang-da-tea-360.webp'}];
async function mockStore(page){await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({status:200,contentType:'text/css',body:''}));await page.route('https://fonts.gstatic.com/**',r=>r.fulfill({status:204,body:''}));await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;const out=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});if(path==='/api/products')return out({products});if(path==='/api/coupons')return out({coupons:[]});if(path==='/api/recommendations')return out({products});if(path==='/api/social-feed')return out({items:[],contents:[],creators:[]});if(path==='/api/health')return out({ok:true,d1:true,version:'1.18.2'});if(path.startsWith('/api/customer/'))return out({authenticated:false},401);return out({ok:true})})}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.clear())});
test('master storefront commerce remains stable under the isolated canonical structural baseline',async({page})=>{
const errors=[];page.on('pageerror',e=>errors.push(e.message));await mockStore(page);await page.goto('/?flagship=master',{waitUntil:'domcontentloaded'});
await page.addScriptTag({url:'/kch-conversion-storefront.js?v=1.32.0'});
await page.addStyleTag({url:'/tshop-v134-structural-storefront.css?v=1.34.5'});
await page.addStyleTag({url:'/tshop-v1345-header-isolation.css?v=1.34.5'});
await page.addScriptTag({url:'/kch-v134-structural-storefront.js?v=1.34.5'});
await expect.poll(()=>page.evaluate(()=>window.__KCH_STRUCTURAL_STOREFRONT__)).toBe('1.34.5');
const shell=page.locator('.kch-master-shell');await expect(shell).toHaveAttribute('data-kch-ui','1.34.5');await expect(page.locator('.kch-master-home')).toBeVisible();await page.waitForTimeout(300);
await expect(page.locator('.kch-master-shell > .kch-structural-canonical-header')).toHaveCount(1);await expect(page.locator('.kch-master-shell .tshop-topbar,.kch-master-shell .topbar')).toHaveCount(0);await expect(page.locator('.kch-master-shell input[type="search"]')).toHaveCount(1);
const viewport=page.viewportSize();if(viewport.width>=700){await expect(page.locator('.kch-master-nav')).toBeVisible();for(const label of ['หน้าหลัก','สินค้าทั้งหมด','สินค้าแนะนำ','สินค้าใหม่','โปรโมชั่น','เกี่ยวกับเรา','ติดต่อเรา'])await expect(page.locator('.kch-master-nav').getByRole('button',{name:label})).toBeVisible()}
await expect(page.locator('.kch-master-showcase')).toHaveCount(3);await expect(page.locator('.kch-master-showcase img[src="/assets/products/chiang-da-tea-360.webp"]')).toBeVisible();
const grid=page.locator('.kch-master-products');await expect(grid).toBeVisible();const rangJued=grid.locator('[data-product="rang-jued-tea-e2e"]');const chiangDa=grid.locator('[data-product="chiang-da-tea-e2e"]');await expect(rangJued).toContainText('ชารางจืด');await expect(rangJued).toHaveAttribute('data-kch-v132-ready','1');await expect(rangJued.getByRole('button',{name:/สั่งซื้อ ชารางจืด/})).toBeVisible();await expect(rangJued).toContainText('฿190');
const search=page.locator('#kch-master-search');await search.fill('ชารางจืด');await expect(rangJued).toBeVisible();await expect(chiangDa).toBeHidden();await expect(chiangDa).toHaveAttribute('data-kch-structural-search','0');await search.fill('');await expect(chiangDa).toBeVisible();await expect(chiangDa).not.toHaveAttribute('data-kch-structural-search');
const bodyText=await page.locator('body').innerText();for(const forbidden of ['ขายแล้ว 0','Verified Purchase','FLASH DEAL','088-5807909','0885807909'])expect(bodyText).not.toContain(forbidden);
const metrics=await page.evaluate(async()=>{const h=document.querySelector('.kch-structural-canonical-header'),s=document.querySelector('#kch-master-search');await new Promise(r=>setTimeout(r,250));return {scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,sameHeader:h===document.querySelector('.kch-structural-canonical-header'),sameSearch:s===document.querySelector('#kch-master-search'),canonicalHeaders:document.querySelectorAll('.kch-master-shell>.kch-structural-canonical-header').length,legacyTopbars:document.querySelectorAll('.kch-master-shell .tshop-topbar,.kch-master-shell .topbar').length,searches:document.querySelectorAll('.kch-master-shell input[type="search"]').length}});expect(metrics.scrollWidth).toBeLessThanOrEqual(metrics.clientWidth+1);expect(metrics.sameHeader).toBe(true);expect(metrics.sameSearch).toBe(true);expect(metrics.canonicalHeaders).toBe(1);expect(metrics.legacyTopbars).toBe(0);expect(metrics.searches).toBe(1);expect(errors).toEqual([]);
});