ALTER TABLE orders ADD COLUMN promotion_code TEXT;
CREATE TABLE IF NOT EXISTS promotions(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('percent','fixed')),value REAL NOT NULL CHECK(value >= 0),min_spend REAL DEFAULT 0,max_discount REAL,stack_with_coupon INTEGER DEFAULT 0,priority INTEGER DEFAULT 0,usage_limit INTEGER,used_count INTEGER DEFAULT 0,active INTEGER DEFAULT 1,starts_at TEXT,ends_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS promotion_redemptions(id INTEGER PRIMARY KEY AUTOINCREMENT,promotion_id INTEGER NOT NULL,order_id INTEGER NOT NULL,customer_id INTEGER,discount_amount REAL NOT NULL CHECK(discount_amount >= 0),created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(promotion_id) REFERENCES promotions(id),FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS review_media(id INTEGER PRIMARY KEY AUTOINCREMENT,review_id INTEGER,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,object_key TEXT UNIQUE NOT NULL,media_type TEXT NOT NULL CHECK(media_type IN ('image','video')),status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(review_id) REFERENCES reviews(id) ON DELETE SET NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE UNIQUE INDEX IF NOT EXISTS idx_reviews_order_product ON reviews(order_id,product_id) WHERE order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_promotions_active_window ON promotions(active,starts_at,ends_at,priority);
CREATE INDEX IF NOT EXISTS idx_promotion_redemptions_order ON promotion_redemptions(order_id);
CREATE INDEX IF NOT EXISTS idx_review_media_review ON review_media(review_id,status);
CREATE INDEX IF NOT EXISTS idx_reviews_product_created ON reviews(product_id,created_at);
ALTER TABLE customers ADD COLUMN last_login_at TEXT;
ALTER TABLE customers ADD COLUMN updated_at TEXT;
ALTER TABLE addresses ADD COLUMN label TEXT;
ALTER TABLE addresses ADD COLUMN updated_at TEXT;
ALTER TABLE shipments ADD COLUMN provider TEXT;
ALTER TABLE shipments ADD COLUMN provider_ref TEXT;
CREATE TABLE IF NOT EXISTS customer_auth_challenges(id INTEGER PRIMARY KEY AUTOINCREMENT,phone TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,consumed_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS customer_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS customer_recent_products(customer_id INTEGER NOT NULL,product_id INTEGER NOT NULL,viewed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(customer_id,product_id),FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS creator_commissions(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,creator_id INTEGER NOT NULL,product_id INTEGER NOT NULL,commission_rate REAL NOT NULL DEFAULT 0 CHECK(commission_rate >= 0 AND commission_rate <= 100),base_amount REAL NOT NULL CHECK(base_amount >= 0),amount REAL NOT NULL CHECK(amount >= 0),status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','eligible','paid','void')),eligible_at TEXT,paid_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(order_id,creator_id,product_id),FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(creator_id) REFERENCES creators(id),FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS shipment_events(id INTEGER PRIMARY KEY AUTOINCREMENT,shipment_id INTEGER NOT NULL,provider TEXT NOT NULL,event_id TEXT NOT NULL,event_code TEXT,status TEXT NOT NULL,note TEXT,occurred_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(provider,event_id),FOREIGN KEY(shipment_id) REFERENCES shipments(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_customer_auth_phone_created ON customer_auth_challenges(phone,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_sessions_token ON customer_sessions(token_hash,expires_at);
CREATE INDEX IF NOT EXISTS idx_customer_sessions_customer ON customer_sessions(customer_id,expires_at);
CREATE INDEX IF NOT EXISTS idx_customer_recent_viewed ON customer_recent_products(customer_id,viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_creator_commissions_creator_status ON creator_commissions(creator_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_creator_commissions_order ON creator_commissions(order_id);
CREATE INDEX IF NOT EXISTS idx_shipment_events_shipment_time ON shipment_events(shipment_id,occurred_at DESC);
ALTER TABLE creator_commissions ADD COLUMN payout_ref TEXT;
ALTER TABLE creator_commissions ADD COLUMN updated_at TEXT;
CREATE TABLE IF NOT EXISTS return_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,customer_id INTEGER NOT NULL,product_id INTEGER NOT NULL,qty INTEGER NOT NULL DEFAULT 1 CHECK(qty > 0),reason_code TEXT NOT NULL CHECK(reason_code IN ('damaged','wrong_item','not_as_described','other')),detail TEXT,status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','reviewing','approved','rejected','cancelled','completed')),resolution_note TEXT,requested_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT,resolved_at TEXT,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE INDEX IF NOT EXISTS idx_return_requests_customer ON return_requests(customer_id,requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_return_requests_status ON return_requests(status,requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_return_requests_order_product ON return_requests(order_id,product_id,status);
ALTER TABLE products ADD COLUMN barcode TEXT;
ALTER TABLE products ADD COLUMN weight_grams INTEGER NOT NULL DEFAULT 0 CHECK(weight_grams >= 0);
ALTER TABLE products ADD COLUMN seo_title TEXT;
ALTER TABLE products ADD COLUMN seo_description TEXT;
CREATE TABLE IF NOT EXISTS product_variants(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,sku TEXT UNIQUE NOT NULL,option_name TEXT NOT NULL DEFAULT 'รูปแบบ',option_value TEXT NOT NULL DEFAULT 'มาตรฐาน',price REAL NOT NULL CHECK(price >= 0),compare_at_price REAL,stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0),low_stock_threshold INTEGER NOT NULL DEFAULT 5 CHECK(low_stock_threshold >= 0),barcode TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS product_media(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,object_key TEXT UNIQUE NOT NULL,media_type TEXT NOT NULL DEFAULT 'image' CHECK(media_type IN ('image')),alt_text TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_type TEXT NOT NULL,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,metadata_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE inventory_movements ADD COLUMN variant_id INTEGER REFERENCES product_variants(id);
CREATE INDEX IF NOT EXISTS idx_product_variants_product ON product_variants(product_id,active,stock);
CREATE INDEX IF NOT EXISTS idx_product_media_product ON product_media(product_id,active,sort_order,id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type,entity_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_variant ON inventory_movements(variant_id,created_at DESC);
INSERT OR IGNORE INTO product_variants(product_id,sku,option_name,option_value,price,compare_at_price,stock,low_stock_threshold,active) SELECT id,sku,'รูปแบบ','มาตรฐาน',price,compare_at_price,stock,low_stock_threshold,active FROM products WHERE sku IS NOT NULL AND TRIM(sku) <> ''