const LETTERS=['ก','ข','ค','ง'];
const APP_KEY='kexam_tax_v1';
const SETS=10;
let bank=null,state=null,currentSet=1,currentIndex=0,timerHandle=null,startTimestamp=null,view='home';

const $=s=>document.querySelector(s);
function loadGlobal(){try{return JSON.parse(localStorage.getItem(APP_KEY)||'{}')}catch{return {}}}
function saveGlobal(g){localStorage.setItem(APP_KEY,JSON.stringify(g))}
function getSetState(setNo){const g=loadGlobal();return g['set'+setNo]||null}
function putSetState(setNo,s){const g=loadGlobal();g['set'+setNo]=s;saveGlobal(g)}
function fmtTime(sec){sec=Math.max(0,Math.floor(sec));const h=String(Math.floor(sec/3600)).padStart(2,'0');const m=String(Math.floor((sec%3600)/60)).padStart(2,'0');const s=String(sec%60).padStart(2,'0');return `${h}:${m}:${s}`}
function esc(x=''){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function footer(){return `<footer class="footer"><div><strong>K-EXAM</strong> | ติวสอบราชการ อาจารย์คิม</div><div>www.k-exam.com &nbsp; | &nbsp; สงวนสิทธิ์ ห้ามทำซ้ำ ดัดแปลง และจำหน่ายโดยไม่ได้รับอนุญาต</div></footer>`}
function header(extra=''){return `<header class="topbar"><div class="brand"><div class="brand-mark">K-EXAM</div><div class="brand-sub">ติวสอบราชการ อาจารย์คิม</div></div><div class="top-title">ระบบทำข้อสอบ</div><div class="top-actions">${extra}</div></header>`}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}

async function loadCompressedSet(setNo){const r=await fetch(`set${setNo}.b64`);if(!r.ok)throw new Error('โหลดข้อสอบไม่สำเร็จ');const b64=(await r.text()).trim();const bin=atob(b64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const ds=new DecompressionStream('gzip');const stream=new Blob([bytes]).stream().pipeThrough(ds);return await new Response(stream).json()}

function renderHome(){stopTimer();view='home';const g=loadGlobal();let cards='';for(let s=1;s<=SETS;s++){const st=g['set'+s];const answered=st?Object.keys(st.answers||{}).length:0;const pct=Math.round(answered);const score=st?.submitted?`${st.score}/100`:(answered?`ทำแล้ว ${answered} ข้อ`:'ยังไม่ได้เริ่ม');cards+=`<div class="set-card" data-set="${s}"><div class="n">ชุดที่ ${s}</div><div class="meta">ข้อ ${(s-1)*100+1}–${s*100} · 100 ข้อ</div><div class="set-progress"><span style="width:${st?.submitted?100:pct}%"></span></div><div class="set-score"><span>${score}</span><span>${st?.submitted?'ดูผล/ทำใหม่':'เริ่มทำข้อสอบ'}</span></div></div>`}
$('#app').innerHTML=`${header()}<main class="page"><section class="home-hero"><div><h1>ข้อสอบนักตรวจสอบภาษีปฏิบัติการ<br>กรมสรรพากร</h1><p>ข้อสอบ 1,000 ข้อ แบ่งเป็น 10 ชุด ชุดละ 100 ข้อ เลือกตอบได้จากโทรศัพท์ แท็บเล็ต และคอมพิวเตอร์ บันทึกความคืบหน้าในอุปกรณ์อัตโนมัติ</p><div style="display:flex;gap:10px;flex-wrap:wrap"><span class="chip">4 ตัวเลือก ก ข ค ง</span><span class="chip">เฉลยหลังส่งข้อสอบ</span><span class="chip">ทำเครื่องหมายทบทวนได้</span></div></div><div class="hero-stat"><span>คลังข้อสอบ</span><strong>1,000</strong><span>ข้อ · K-EXAM โดยอาจารย์คิม</span></div></section><div class="section-title">เลือกชุดข้อสอบ</div><section class="sets">${cards}</section></main>${footer()}`;
document.querySelectorAll('.set-card').forEach(el=>el.onclick=()=>openSet(+el.dataset.set));}

async function openSet(setNo){currentSet=setNo;const old=getSetState(setNo);if(old?.submitted){showStartDialog(setNo,old,true);return}showStartDialog(setNo,old,false)}
function showStartDialog(setNo,old,submitted){const remaining=old?100-Object.keys(old.answers||{}).length:100;const title=submitted?'ชุดนี้ทำเสร็จแล้ว':old?'ทำต่อจากครั้งก่อน':'เริ่มทำข้อสอบ';const msg=submitted?`คะแนนล่าสุด ${old.score}/100 คุณสามารถดูผลเดิมหรือเริ่มทำใหม่ได้`:(old?`มีคำตอบที่บันทึกไว้ ${100-remaining} ข้อ ระบบจะเปิดต่อจากเดิม`:'ระบบจะบันทึกคำตอบไว้ในอุปกรณ์นี้โดยอัตโนมัติ และจะไม่แสดงเฉลยจนกว่าจะส่งข้อสอบ');const actions=submitted?`<button class="ghost-btn" id="viewResultBtn">ดูผลเดิม</button><button class="danger-btn" id="newAttemptBtn">เริ่มใหม่</button>`:`<button class="ghost-btn" id="cancelModal">ยกเลิก</button><button class="primary-btn" id="beginBtn">${old?'ทำต่อ':'เริ่มทำข้อสอบ'}</button>`;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="startModal"><div class="modal"><h3>${title} · ชุดที่ ${setNo}</h3><p>${msg}</p><div class="modal-actions">${actions}</div></div></div>`);$('#cancelModal')&&($('#cancelModal').onclick=()=>$('#startModal').remove());$('#beginBtn')&&($('#beginBtn').onclick=()=>{ $('#startModal').remove(); beginExam(setNo,false)});$('#viewResultBtn')&&($('#viewResultBtn').onclick=()=>{$('#startModal').remove();beginExam(setNo,false,true)});$('#newAttemptBtn')&&($('#newAttemptBtn').onclick=()=>{$('#startModal').remove();beginExam(setNo,true)});}

async function beginExam(setNo,reset=false,showResult=false){bank=await loadCompressedSet(setNo);let st=getSetState(setNo);if(reset||!st){st={answers:{},flags:{},startedAt:Date.now(),elapsed:0,submitted:false,score:null,lastIndex:0};putSetState(setNo,st)}state=st;currentIndex=Math.min(99,state.lastIndex||0);if(showResult||state.submitted){renderResult();return}startTimestamp=Date.now();startTimer();renderExam();}
function startTimer(){stopTimer();timerHandle=setInterval(()=>{const t=$('#timer');if(t&&state&&!state.submitted){const base=state.elapsed||0;const sec=base+(Date.now()-startTimestamp)/1000;t.textContent=fmtTime(sec)}},1000)}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function persist(){if(!state||state.submitted)return;if(startTimestamp){state.elapsed=(state.elapsed||0)+(Date.now()-startTimestamp)/1000;startTimestamp=Date.now()}state.lastIndex=currentIndex;putSetState(currentSet,state)}
window.addEventListener('beforeunload',persist);

function answeredCount(){return Object.keys(state.answers||{}).length}function flagCount(){return Object.values(state.flags||{}).filter(Boolean).length}
function categoryStats(){const map={};bank.questions.forEach((q,i)=>{map[q.category]=map[q.category]||{total:0,answered:0};map[q.category].total++;if(state.answers[i]!==undefined)map[q.category].answered++});return map}
function renderExam(){view='exam';const q=bank.questions[currentIndex];const answered=answeredCount(),flags=flagCount();let grid='';for(let i=0;i<100;i++){const cl=['qnum'];if(state.answers[i]!==undefined)cl.push('answered');if(state.flags[i])cl.push('flagged');if(i===currentIndex)cl.push('current');grid+=`<button class="${cl.join(' ')}" data-i="${i}">${i+1}</button>`}let choices=q.choices.map((c,i)=>`<button class="choice ${state.answers[currentIndex]===i?'selected':''}" data-choice="${i}"><span class="choice-letter">${LETTERS[i]}</span><span>${esc(c)}</span></button>`).join('');const cats=categoryStats();const catHtml=Object.entries(cats).map(([k,v])=>`<div class="cat-row"><div class="label"><span>${esc(k)}</span><span>${v.answered}/${v.total}</span></div><div class="bar"><span style="width:${v.total?100*v.answered/v.total:0}%"></span></div></div>`).join('');const extra=`<span class="chip">ชุดที่ ${currentSet}</span><span class="chip">ข้อ ${(currentSet-1)*100+1}–${currentSet*100}</span><span class="timer" id="timer">${fmtTime((state.elapsed||0)+(startTimestamp?(Date.now()-startTimestamp)/1000:0))}</span>`;
$('#app').innerHTML=`${header(extra)}<main class="page"><div class="exam-grid"><aside class="panel left-panel"><h3>แผงข้อสอบ</h3><div class="legend"><span><i class="dot a"></i>ตอบแล้ว</span><span><i class="dot u"></i>ยังไม่ตอบ</span><span><i class="dot f"></i>ทบทวน</span></div><div class="qgrid">${grid}</div></aside><section class="panel main-panel"><div class="progress-row"><div class="progress-title">ข้อ ${currentIndex+1} / 100</div><div class="progressbar"><span style="width:${currentIndex+1}%"></span></div><button class="ghost-btn" id="flagBtn">${state.flags[currentIndex]?'✓ ทำเครื่องหมายแล้ว':'⚑ ทำเครื่องหมายไว้'}</button></div><div class="question-card"><div class="category">${esc(q.category)}</div><div class="question">${esc(q.prompt)}</div><div class="choices">${choices}</div><div class="copyright-note">จัดทำโดย อาจารย์คิม · www.k-exam.com · สงวนสิทธิ์ ห้ามทำซ้ำ ดัดแปลง และจำหน่ายโดยไม่ได้รับอนุญาต</div></div><div class="exam-actions"><div class="action-left"><button class="ghost-btn" id="prevBtn">← ข้อก่อนหน้า</button><button class="ghost-btn" id="clearBtn">ล้างคำตอบ</button></div><div class="action-right"><button class="primary-btn" id="nextBtn">ข้อถัดไป →</button><button class="primary-btn" id="submitBtn" style="background:#083f94">ส่งข้อสอบ</button></div></div></section><aside class="panel right-panel"><div class="stat-card"><div class="time-label">เวลาที่ใช้</div><div class="time-value" id="timeRight">${fmtTime((state.elapsed||0)+(startTimestamp?(Date.now()-startTimestamp)/1000:0))}</div></div><div class="stat-row"><div class="mini green"><span>ตอบแล้ว</span><div class="v">${answered}</div><small>จาก 100 ข้อ</small></div><div class="mini gray"><span>ยังไม่ตอบ</span><div class="v">${100-answered}</div><small>จาก 100 ข้อ</small></div><div class="mini red"><span>ทบทวน</span><div class="v">${flags}</div><small>ทำเครื่องหมาย</small></div><div class="mini"><span>ความคืบหน้า</span><div class="v">${answered}%</div><small>ตอบแล้ว</small></div></div><h3 style="margin-top:18px">สัดส่วนเนื้อหา</h3>${catHtml}</aside></div></main><div class="mobile-nav"><button class="ghost-btn" id="mPrev">← ก่อนหน้า</button><button class="ghost-btn" id="mFlag">⚑ ทบทวน</button><button class="primary-btn" id="mNext">ถัดไป →</button></div>${footer()}`;
const tr=$('#timeRight');if(tr){stopTimer();timerHandle=setInterval(()=>{const sec=(state.elapsed||0)+(Date.now()-startTimestamp)/1000;$('#timer')&&($('#timer').textContent=fmtTime(sec));$('#timeRight')&&($('#timeRight').textContent=fmtTime(sec))},1000)}
document.querySelectorAll('.qnum').forEach(b=>b.onclick=()=>goto(+b.dataset.i));document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>selectChoice(+b.dataset.choice));$('#flagBtn').onclick=toggleFlag;$('#prevBtn').onclick=()=>goto(currentIndex-1);$('#nextBtn').onclick=()=>goto(currentIndex+1);$('#clearBtn').onclick=clearAnswer;$('#submitBtn').onclick=confirmSubmit;$('#mPrev').onclick=()=>goto(currentIndex-1);$('#mNext').onclick=()=>goto(currentIndex+1);$('#mFlag').onclick=toggleFlag;}
function goto(i){if(i<0||i>99)return;persist();currentIndex=i;renderExam();window.scrollTo({top:0,behavior:'smooth'})}
function selectChoice(i){state.answers[currentIndex]=i;persist();renderExam()}
function clearAnswer(){delete state.answers[currentIndex];persist();renderExam();toast('ล้างคำตอบแล้ว')}
function toggleFlag(){state.flags[currentIndex]=!state.flags[currentIndex];persist();renderExam()}
function confirmSubmit(){persist();const left=100-answeredCount();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="submitModal"><div class="modal"><h3>ยืนยันส่งข้อสอบ</h3><p>${left?`ยังไม่ได้ตอบ ${left} ข้อ คุณสามารถกลับไปทำต่อหรือส่งข้อสอบได้ทันที`:'ตอบครบทั้ง 100 ข้อแล้ว พร้อมตรวจคะแนน'}</p><div class="modal-actions"><button class="ghost-btn" id="backExam">กลับไปทำต่อ</button><button class="primary-btn" id="confirmSubmit">ส่งข้อสอบ</button></div></div></div>`);$('#backExam').onclick=()=>$('#submitModal').remove();$('#confirmSubmit').onclick=()=>{$('#submitModal').remove();submitExam()}}
function submitExam(){persist();let score=0;bank.questions.forEach((q,i)=>{if(state.answers[i]===q.correctIndex)score++});state.submitted=true;state.score=score;state.submittedAt=Date.now();putSetState(currentSet,state);stopTimer();renderResult()}
function renderResult(){view='result';stopTimer();const score=state.score??0;const answered=Object.keys(state.answers||{}).length;const wrong=answered-score;const un=100-answered;const cats={};bank.questions.forEach((q,i)=>{cats[q.category]=cats[q.category]||{total:0,correct:0};cats[q.category].total++;if(state.answers[i]===q.correctIndex)cats[q.category].correct++});let catCards=Object.entries(cats).map(([k,v])=>`<div class="result-box"><span>${esc(k)}</span><strong>${v.correct}/${v.total}</strong><small>${Math.round(v.correct/v.total*100)}%</small></div>`).join('');let reviews=bank.questions.map((q,i)=>{const a=state.answers[i],ok=a===q.correctIndex;return `<article class="review ${ok?'correct':'wrong'}"><h4>ข้อ ${i+1} ${ok?'✓ ถูกต้อง':'✕ ตรวจทาน'}</h4><div>${esc(q.prompt)}</div><div class="ans">คำตอบของคุณ: ${a===undefined?'ไม่ได้ตอบ':LETTERS[a]+'. '+esc(q.choices[a])}</div><div class="ans"><strong>คำตอบที่ถูก: ${LETTERS[q.correctIndex]}. ${esc(q.choices[q.correctIndex])}</strong></div>${q.explanation?`<div class="explain"><strong>อธิบายเพิ่มเติม:</strong> ${esc(q.explanation)}</div>`:''}</article>`}).join('');
$('#app').innerHTML=`${header(`<span class="chip">ชุดที่ ${currentSet}</span>`)}<main class="page result-wrap"><section class="score-card"><div><div>ผลการทำข้อสอบ</div><div class="score-big">${score}/100</div><div class="score-meta">คิดเป็น ${score}% · ใช้เวลา ${fmtTime(state.elapsed||0)}</div></div><div><button class="ghost-btn" id="homeBtn">กลับหน้าหลัก</button> <button class="ghost-btn" id="wrongOnlyBtn">ดูเฉพาะข้อที่ผิด</button> <button class="danger-btn" id="retryBtn">ทำชุดนี้ใหม่</button></div></section><section class="result-grid"><div class="result-box"><span>ตอบถูก</span><strong style="color:var(--green)">${score}</strong></div><div class="result-box"><span>ตอบผิด</span><strong style="color:var(--red)">${wrong}</strong></div><div class="result-box"><span>ไม่ได้ตอบ</span><strong>${un}</strong></div><div class="result-box"><span>ทำเครื่องหมายไว้</span><strong>${flagCount()}</strong></div>${catCards}</section><div class="section-title">ทบทวนคำตอบ</div><section class="review-list" id="reviewList">${reviews}</section></main>${footer()}`;$('#homeBtn').onclick=renderHome;$('#retryBtn').onclick=()=>{const g=loadGlobal();delete g['set'+currentSet];saveGlobal(g);beginExam(currentSet,true)};$('#wrongOnlyBtn').onclick=()=>{document.querySelectorAll('.review.correct').forEach(x=>x.classList.toggle('hidden'));$('#wrongOnlyBtn').textContent=$('#wrongOnlyBtn').textContent.includes('เฉพาะ')?'แสดงทุกข้อ':'ดูเฉพาะข้อที่ผิด'};}

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
renderHome();
