import {json,sameOrigin,securityEvent} from '../../_lib/staff-auth.js';
const actor=request=>({id:Number(request.headers.get('X-KCH-Staff-Id'))||null,name:request.headers.get('X-KCH-Staff-Name')||'legacy'});
export async function onRequestGet({env}){if(!env.DB)return json({error:'database_not_bound'},503);const r=await env.DB.prepare(`SELECT ar.*,u.username requested_by_username,u.display_name requested_by_name,
  (SELECT COUNT(*) FROM approval_decisions d WHERE d.approval_request_id=ar.id AND d.decision='approved') approvals_count
  FROM approval_requests ar JOIN staff_users u ON u.id=ar.requested_by ORDER BY CASE ar.status WHEN 'pending' THEN 0 ELSE 1 END,ar.id DESC LIMIT 200`).all();return json({requests:r.results||[]})}
export async function onRequestPost({request,env}){
  if(!sameOrigin(request))return json({error:'invalid_origin'},403);const a=actor(request);if(!a.id)return json({error:'staff_session_required_for_approval'},403);const b=await request.json().catch(()=>({})),id=Number(b.id),decision=String(b.decision||''),note=String(b.note||'').trim().slice(0,500);if(!id||!['approved','rejected'].includes(decision))return json({error:'invalid_decision'},400);
  const ar=await env.DB.prepare("SELECT * FROM approval_requests WHERE id=?").bind(id).first();if(!ar)return json({error:'approval_not_found'},404);if(ar.status!=='pending')return json({error:'approval_resolved'},409);if(Number(ar.requested_by)===a.id)return json({error:'requester_cannot_approve'},409);
  try{await env.DB.prepare("INSERT INTO approval_decisions(approval_request_id,staff_user_id,decision,note) VALUES(?,?,?,?)").bind(id,a.id,decision,note||null).run()}catch{return json({error:'already_decided'},409)}
  if(decision==='rejected'){await env.DB.prepare("UPDATE approval_requests SET status='rejected',resolved_at=datetime('now'),resolution_note=? WHERE id=?").bind(note||'rejected',id).run();await securityEvent(env,{staffUserId:a.id,eventType:'approval_rejected',severity:'warning',route:'/api/admin/approvals',method:'POST',statusCode:200,detail:{id,actionKey:ar.action_key,entityId:ar.entity_id}});return json({ok:true,status:'rejected'})}
  const c=await env.DB.prepare("SELECT COUNT(*) c FROM approval_decisions WHERE approval_request_id=? AND decision='approved'").bind(id).first();if(Number(c?.c||0)>=Number(ar.required_approvals||1)){
    const batch=[env.DB.prepare("UPDATE approval_requests SET status='approved',resolved_at=datetime('now'),resolution_note=? WHERE id=?").bind(note||'approved',id)];
    if(ar.action_key==='procurement.approve')batch.push(env.DB.prepare("UPDATE purchase_orders SET approval_status='approved',status='ordered',approved_by=?,approved_at=datetime('now'),rejection_note=NULL,updated_at=datetime('now') WHERE po_no=? AND approval_status='pending'").bind(a.name,ar.entity_id));
    batch.push(env.DB.prepare("INSERT INTO audit_logs(actor_type,actor_id,action,entity_type,entity_id,metadata_json) VALUES('staff',?,'approval.resolve',?,?,?)").bind(a.name,ar.entity_type,ar.entity_id,JSON.stringify({approvalRequestId:id,actionKey:ar.action_key,decision:'approved'})));await env.DB.batch(batch);await securityEvent(env,{staffUserId:a.id,eventType:'approval_completed',route:'/api/admin/approvals',method:'POST',statusCode:200,detail:{id,actionKey:ar.action_key,entityId:ar.entity_id}});return json({ok:true,status:'approved',executed:ar.action_key==='procurement.approve'})
  }
  return json({ok:true,status:'pending',approvals:Number(c?.c||0),required:Number(ar.required_approvals||1)});
}
