import {json,sameOrigin,safeUsername,randomHex,derivePassword,legacyAuthorized,securityEvent} from '../../_lib/staff-auth.js';
const ROLES=new Set(['owner','admin','operations','warehouse','finance','support','viewer']);
const actor=request=>({id:Number(request.headers.get('X-KCH-Staff-Id'))||null,name:request.headers.get('X-KCH-Staff-Name')||'legacy'});
async function passwordParts(env,password){password=String(password||'');if(password.length<12||password.length>200)throw new Error('weak_password');const salt=randomHex(16),iterations=Math.min(600000,Math.max(100000,Number(env.STAFF_PASSWORD_ITERATIONS||180000))),hash=await derivePassword(password,salt,iterations);return {salt,iterations,hash}}
export async function onRequestGet({request,env}){if(!env.DB)return json({error:'database_not_bound'},503);const a=actor(request),rows=await env.DB.prepare(`SELECT u.id,u.username,u.display_name,u.role,u.active,u.failed_login_count,u.locked_until,u.last_login_at,u.created_at,
  COALESCE(SUM(CASE WHEN s.revoked_at IS NULL AND s.expires_at>datetime('now') THEN 1 ELSE 0 END),0) active_sessions
  FROM staff_users u LEFT JOIN staff_sessions s ON s.staff_user_id=u.id GROUP BY u.id ORDER BY u.active DESC,u.role,u.username`).all();return json({staff:rows.results||[],actor:a,legacy:!a.id})}
export async function onRequestPost({request,env}){
  if(!sameOrigin(request))return json({error:'invalid_origin'},403);if(!env.DB)return json({error:'database_not_bound'},503);const b=await request.json().catch(()=>({})),action=String(b.action||''),a=actor(request),isLegacy=!a.id&&legacyAuthorized(request,env);
  if(action==='bootstrap_owner'){
    const count=await env.DB.prepare('SELECT COUNT(*) c FROM staff_users WHERE active=1').first();if(Number(count?.c||0)>0)return json({error:'staff_already_initialized'},409);if(!isLegacy)return json({error:'legacy_bootstrap_required'},403);const username=safeUsername(b.username),displayName=String(b.displayName||'').trim().slice(0,120);if(!username||displayName.length<2)return json({error:'invalid_staff'},400);let p;try{p=await passwordParts(env,b.password)}catch{return json({error:'password_min_12'},400)}await env.DB.prepare("INSERT INTO staff_users(username,display_name,role,password_hash,password_salt,password_iterations,created_by) VALUES(?,?,'owner',?,?,?,'legacy-bootstrap')").bind(username,displayName,p.hash,p.salt,p.iterations).run();await securityEvent(env,{eventType:'staff_owner_bootstrapped',severity:'warning',route:'/api/admin/staff',method:'POST',statusCode:200,detail:{username}});return json({ok:true})
  }
  if(action==='create_staff'){
    const username=safeUsername(b.username),displayName=String(b.displayName||'').trim().slice(0,120),role=String(b.role||'viewer');if(!username||displayName.length<2||!ROLES.has(role))return json({error:'invalid_staff'},400);let p;try{p=await passwordParts(env,b.password)}catch{return json({error:'password_min_12'},400)}try{const r=await env.DB.prepare("INSERT INTO staff_users(username,display_name,role,password_hash,password_salt,password_iterations,created_by) VALUES(?,?,?,?,?,?,?) RETURNING id").bind(username,displayName,role,p.hash,p.salt,p.iterations,a.name).first();await securityEvent(env,{staffUserId:a.id,eventType:'staff_created',route:'/api/admin/staff',method:'POST',statusCode:200,detail:{staffId:r?.id,username,role}});return json({ok:true,id:r?.id})}catch{return json({error:'duplicate_username'},409)}
  }
  const id=Number(b.id);if(!id)return json({error:'staff_id_required'},400);if(a.id===id&&['set_active','set_role'].includes(action))return json({error:'cannot_change_own_access'},409);const target=await env.DB.prepare('SELECT id,username,role,active FROM staff_users WHERE id=?').bind(id).first();if(!target)return json({error:'staff_not_found'},404);
  if(action==='set_active'){const active=b.active?1:0;await env.DB.batch([env.DB.prepare("UPDATE staff_users SET active=?,updated_at=datetime('now') WHERE id=?").bind(active,id),env.DB.prepare("UPDATE staff_sessions SET revoked_at=datetime('now') WHERE staff_user_id=? AND revoked_at IS NULL").bind(id)]);await securityEvent(env,{staffUserId:a.id,eventType:'staff_active_changed',route:'/api/admin/staff',method:'POST',statusCode:200,detail:{target:id,active}});return json({ok:true})}
  if(action==='set_role'){const role=String(b.role||'');if(!ROLES.has(role))return json({error:'invalid_role'},400);await env.DB.batch([env.DB.prepare("UPDATE staff_users SET role=?,updated_at=datetime('now') WHERE id=?").bind(role,id),env.DB.prepare("UPDATE staff_sessions SET revoked_at=datetime('now') WHERE staff_user_id=? AND revoked_at IS NULL").bind(id)]);await securityEvent(env,{staffUserId:a.id,eventType:'staff_role_changed',route:'/api/admin/staff',method:'POST',statusCode:200,detail:{target:id,role}});return json({ok:true})}
  if(action==='reset_password'){let p;try{p=await passwordParts(env,b.password)}catch{return json({error:'password_min_12'},400)}await env.DB.batch([env.DB.prepare("UPDATE staff_users SET password_hash=?,password_salt=?,password_iterations=?,password_changed_at=datetime('now'),failed_login_count=0,locked_until=NULL,updated_at=datetime('now') WHERE id=?").bind(p.hash,p.salt,p.iterations,id),env.DB.prepare("UPDATE staff_sessions SET revoked_at=datetime('now') WHERE staff_user_id=? AND revoked_at IS NULL").bind(id)]);await securityEvent(env,{staffUserId:a.id,eventType:'staff_password_reset',severity:'warning',route:'/api/admin/staff',method:'POST',statusCode:200,detail:{target:id}});return json({ok:true})}
  return json({error:'invalid_action'},400);
}
